#!/bin/bash

# 🎤 Voice Service Production Deployment Fix
# This script provides the exact environment variables needed for Render

echo "🎤 VOICE SERVICE PRODUCTION DEPLOYMENT FIX"
echo "==========================================="
echo ""
echo "The voice service is working locally but failing in production because"
echo "the ElevenLabs environment variables are not set in Render."
echo ""
echo "🔧 REQUIRED ACTION: Set these environment variables in Render Dashboard"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Select your 'isaac-mineo-api' service"  
echo "3. Go to 'Environment' tab"
echo "4. Add these environment variables:"
echo ""
echo "   Variable Name: DEEPGRAM_API_KEY"
echo "   Value: ab8f08f0c45817b06eab22c496ecd309a9e8ef76"
echo "   Environment: Production"
echo ""
echo "   Variable Name: ELEVENLABS_API_KEY" 
echo "   Value: sk_622c172467fe46ecad141435f8d47e630ba7e812ab2989ac"
echo "   Environment: Production"
echo ""
echo "   Variable Name: ELEVENLABS_VOICE_ID"
echo "   Value: 1RK8FVAmOrgVnhf48vx1"
echo "   Environment: Production"
echo ""
echo "5. Click 'Save' (this will trigger a redeploy)"
echo ""
echo "⏱️  After the redeploy (2-3 minutes), test with:"
echo "   curl https://isaac-mineo-api.onrender.com/api/voice/status"
echo ""
echo "✅ Expected result after fix:"
echo "   voice_enabled: true"
echo "   deepgram_available: true" 
echo "   elevenlabs_available: true"
echo "   status: 'Voice services ready'"
echo ""
echo "🎯 Once this is done, your production voice service will be 100% functional!"
